## Import Libraries

In [ ]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Get Data

In [ ]:
fashion_df = keras.datasets.fashion_mnist
( X_train , y_train ), ( X_test , y_test ) = fashion_df.load_data ()
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [ ]:
X_train = pd.DataFrame(X_train.reshape(60000,784))
X_test = pd.DataFrame(X_test.reshape(10000,784))
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)


In [ ]:
print (X_train.shape, y_train.shape, X_test.shape, y_test.shape)
y_test.head(10)

(60000, 784) (60000, 1) (10000, 784) (10000, 1)


0
0  9
1  2
2  1
3  1
4  6
5  1
6  4
7  6
8  5
9  7

##Assignment

Above dataset has images of different types of merchandise (structure is the same as digit recognition dataset). Numerical labels correspond to the following types of goods - 
1. T-shirt/top
2. Trouser
3. Pullover
4. Dress
5. Coat
6. Sandal
7. Shirt
8. Sneaker
9. Bag
10. Ankle boot

You are required to experiment with different classification models and select the best model for classification of images in the given dataset.

Through cross valiation assess if the results are consistent.

Perform hyperparameter tuning on the selected model(s).

You may refer to the digit classification exercise for getting guiance but try performing the entire sequence on your owns. 

Trying out SGD Classifier

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn import metrics
lm = SGDClassifier(random_state=42)
lm.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
y_pred = lm.predict(X_test)
print(y_pred)

[9 2 1 ... 8 1 5]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm = pd.DataFrame(cm)
cm.style.background_gradient(cmap ='coolwarm')
print(cm)
accuracy_test = accuracy_score(y_test,y_pred)
print("accuracy =",accuracy_test)

     0    1    2    3    4    5    6    7    8    9
0  761    4   12   73    6    1  126    0   17    0
1    1  944    5   35    5    0    9    0    1    0
2    9    1  704   17  128    0  130    0   11    0
3   31    9   13  870   28    0   46    0    3    0
4    1    0  111   57  724    0  106    0    1    0
5    1    0    0    0    0  926    2   34   10   27
6  132    2  107   73   93    0  557    0   36    0
7    0    0    0    0    0   48    0  917    2   33
8    5    1    3   15    2    1   33    5  935    0
9    0    0    0    1    0   15    2   36    1  945
accuracy = 0.8283


In [ ]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.76      0.78      1000
           1       0.98      0.94      0.96      1000
           2       0.74      0.70      0.72      1000
           3       0.76      0.87      0.81      1000
           4       0.73      0.72      0.73      1000
           5       0.93      0.93      0.93      1000
           6       0.55      0.56      0.55      1000
           7       0.92      0.92      0.92      1000
           8       0.92      0.94      0.93      1000
           9       0.94      0.94      0.94      1000

    accuracy                           0.83     10000
   macro avg       0.83      0.83      0.83     10000
weighted avg       0.83      0.83      0.83     10000



In [ ]:
from sklearn.model_selection import cross_val_score
cvs = cross_val_score(lm, X_train, y_train, cv = 3, scoring = 'accuracy')
print (cvs)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/l

[0.83035 0.83545 0.83725]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SVC Classifier

In [ ]:
from sklearn.svm import SVC
from sklearn import metrics
lm = SVC()
lm.fit(X_train, y_train)
predictions = lm.predict(X_test)
print(predictions)
con_matrix = pd.DataFrame(metrics.confusion_matrix(y_test, predictions))
print(con_matrix)
print('Classification metrics for SVC classifier')
print()
print('Score on Test Data ',' '*5, '%0.2f' %(lm.score(X_test, y_test)))
print('RMSE               ',' '*5, '%0.2f' %(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
print('Mean Absolute Error',' '*5, '%0.2f' %(metrics.mean_absolute_error(y_test, predictions)))
print()
print("Classification report")
print()
print(con_matrix.style.background_gradient(cmap='coolwarm'))
print()
print((metrics.classification_report(y_test, predictions)))
print()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[9 2 1 ... 8 1 5]
     0    1    2    3    4    5    6    7    8    9
0  856    0    9   29    3    1   90    0   12    0
1    4  961    3   25    3    0    4    0    0    0
2   13    1  815   12   92    0   64    0    3    0
3   28    3   12  893   31    0   29    0    4    0
4    0    0   84   30  821    0   61    0    4    0
5    0    0    0    1    0  958    0   26    2   13
6  142    1   92   31   67    0  647    0   20    0
7    0    0    0    0    0   20    0  959    0   21
8    3    0    2    5    4    4    3    4  974    1
9    0    0    0    0    0    8    0   37    3  952
Classification metrics for SVC classifier

Score on Test Data        0.88
RMSE                      1.27
Mean Absolute Error       15.39

Classification report


              precision    recall  f1-score   support

           0       0.82      0.86      0.84      1000
           1       0.99      0.96      0.98      1000
           2       0.80      0.81      0.81      1000
           3       0.87      0.